### ISSUE TITLE
Playback issues

### ISSUE THREAD

**Issue by Gaster666** [dubtrack/www-dubtrack-fm#313]
I have tried in multiple rooms, and so has my friend, to play some songs, and the songs don;t play. The only screen we both see is the one that says "Click here to begin", and we queued multiple songs. Here is the main room we are having the problem in, and I am not sure if it is occurring with anybody else.

https://www.dubtrack.fm/join/frens

**Comment by starnixce** [comment]
Sorry about that. Should be working now.

**Comment by Jazzerus** [comment]
I'm having the same problem.

**Comment by ghost** [comment]
the same thing happened to me but now all the rooms are working and only ours that is not running queue

**Comment by Al3366** [comment]
Hi all,

Sorry about the issues you've been having recently. Our system hasn't been feeling very well lately, but as of right now Dubtrack looks to be stable and running fine. We will continue to monitor the service for the time being. If any more issues do arise, please do let us know here.

**Comment by ghost** [comment]
@Al3366 The problem still persists in the room and I can not put any music. What happened?

**Comment by Al3366** [comment]
@Githubguy11 I don't know for sure what is happening, but I am sure once we resolve the issues we will do a full post-mortem to see what happened.

**Comment by ghost** [comment]
Ok Thanks.

**Comment by Al3366** [comment]
Update here: https://github.com/dubtrack/www-dubtrack-fm/issues/314
